export const SET_TODO_SUCCESS = 'SET_TODO_SUCCESS';

export const SET_TODO_ERROR = 'SET_TODO_ERROR';

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';

export const LOADING = 'LOADING';

export const GET_TODO_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';

export const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS';

export const COMPLETE_TODO_ERROR = 'COMPLETE_TODO_ERROR';

export const GET_TODO_LIST_ERROR = 'GET_TODO_LIST_ERROR';